trainer:
  gpus: 1  # single GPU training
  min_epochs: 20
  max_epochs: 100
  benchmark: True
program:
   data_dir: '/home/esther/torchgeo_data/cvpr_chesapeake_landcover'
   overwrite: True
experiment:
  task: "chesapeake_learn_the_prior"
  name: "chesapeake_learn_prior_l2"
  module:
    loss: "nll"  # cross entropy loss
    segmentation_model: "fcn"
    optimizer: "adamw"
    learning_rate: 1e-3
    learning_rate_schedule_patience: 4
  datamodule:
    batch_size: 32
    num_workers: 4
    patches_per_tile: 100
    train_state: "de" # train/val/test in Delaware
    onehot_encode_labels: False